### ISSUE TITLE
Remove repos which have corrected models

### ISSUE THREAD

**Issue by troycomi** [jeromekelleher/msprime-model-errors#7]
Thank you so much for reporting this to affected projects!  Thankfully we don't use that model for much and the other models use the MassMigration/MigrationRateChange properly. I have pushed the correction to https://github.com/PrincetonUniversity/msprime_scripts closing that issue.  Will you keep track of closed issues and remove them from this repo or should I submit a PR here?

**Comment by jeromekelleher** [comment]
Thanks @troycomi, I'm relieved to hear you're not too badly affected. A PR would be really helpful - maybe start a new subsection where we move the repos with corrected model implementations?

**Comment by troycomi** [comment]
Done and closing.
